import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
    ALTER TABLE "about_page"
      ADD COLUMN IF NOT EXISTS "hero_headline"      varchar,
      ADD COLUMN IF NOT EXISTS "hero_description"   text,
      ADD COLUMN IF NOT EXISTS "stat1_number"       varchar,
      ADD COLUMN IF NOT EXISTS "stat1_label"        varchar,
      ADD COLUMN IF NOT EXISTS "stat2_number"       varchar,
      ADD COLUMN IF NOT EXISTS "stat2_label"        varchar,
      ADD COLUMN IF NOT EXISTS "stat3_number"       varchar,
      ADD COLUMN IF NOT EXISTS "stat3_label"        varchar,
      ADD COLUMN IF NOT EXISTS "ffl_license_number" varchar,

      ADD COLUMN IF NOT EXISTS "excellence_heading" varchar,
      ADD COLUMN IF NOT EXISTS "excellence_body"    text,
      ADD COLUMN IF NOT EXISTS "excellence_italic"  text,

      ADD COLUMN IF NOT EXISTS "story_heading"      varchar,
      ADD COLUMN IF NOT EXISTS "story_para1"        text,
      ADD COLUMN IF NOT EXISTS "story_para2"        text,
      ADD COLUMN IF NOT EXISTS "story_para3"        text,
      ADD COLUMN IF NOT EXISTS "story_para4"        text,
      ADD COLUMN IF NOT EXISTS "story_pullquote"    varchar,
      ADD COLUMN IF NOT EXISTS "story_para_final"   text,

      ADD COLUMN IF NOT EXISTS "phil1_title"        varchar,
      ADD COLUMN IF NOT EXISTS "phil1_body"         text,
      ADD COLUMN IF NOT EXISTS "phil2_title"        varchar,
      ADD COLUMN IF NOT EXISTS "phil2_body"         text,
      ADD COLUMN IF NOT EXISTS "phil3_title"        varchar,
      ADD COLUMN IF NOT EXISTS "phil3_body"         text,

      ADD COLUMN IF NOT EXISTS "mission_heading"    varchar,
      ADD COLUMN IF NOT EXISTS "mission_body1"      text,
      ADD COLUMN IF NOT EXISTS "mission_body2"      text,
      ADD COLUMN IF NOT EXISTS "mission_callout"    varchar,
      ADD COLUMN IF NOT EXISTS "pillar1_title"      varchar,
      ADD COLUMN IF NOT EXISTS "pillar1_body"       text,
      ADD COLUMN IF NOT EXISTS "pillar2_title"      varchar,
      ADD COLUMN IF NOT EXISTS "pillar2_body"       text,
      ADD COLUMN IF NOT EXISTS "pillar3_title"      varchar,
      ADD COLUMN IF NOT EXISTS "pillar3_body"       text,
      ADD COLUMN IF NOT EXISTS "pillar4_title"      varchar,
      ADD COLUMN IF NOT EXISTS "pillar4_body"       text,

      ADD COLUMN IF NOT EXISTS "curation_heading"   varchar,
      ADD COLUMN IF NOT EXISTS "curation_intro"     text,
      ADD COLUMN IF NOT EXISTS "crit1_title"        varchar,
      ADD COLUMN IF NOT EXISTS "crit1_body"         varchar,
      ADD COLUMN IF NOT EXISTS "crit2_title"        varchar,
      ADD COLUMN IF NOT EXISTS "crit2_body"         varchar,
      ADD COLUMN IF NOT EXISTS "crit3_title"        varchar,
      ADD COLUMN IF NOT EXISTS "crit3_body"         varchar,
      ADD COLUMN IF NOT EXISTS "crit4_title"        varchar,
      ADD COLUMN IF NOT EXISTS "crit4_body"         varchar,

      ADD COLUMN IF NOT EXISTS "ffl_body"           text,
      ADD COLUMN IF NOT EXISTS "ffl_card1_body"     varchar,
      ADD COLUMN IF NOT EXISTS "ffl_card2_body"     varchar;
  `)
}

export async function down({ db }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
    ALTER TABLE "about_page"
      DROP COLUMN IF EXISTS "hero_headline",
      DROP COLUMN IF EXISTS "hero_description",
      DROP COLUMN IF EXISTS "stat1_number",
      DROP COLUMN IF EXISTS "stat1_label",
      DROP COLUMN IF EXISTS "stat2_number",
      DROP COLUMN IF EXISTS "stat2_label",
      DROP COLUMN IF EXISTS "stat3_number",
      DROP COLUMN IF EXISTS "stat3_label",
      DROP COLUMN IF EXISTS "ffl_license_number",
      DROP COLUMN IF EXISTS "excellence_heading",
      DROP COLUMN IF EXISTS "excellence_body",
      DROP COLUMN IF EXISTS "excellence_italic",
      DROP COLUMN IF EXISTS "story_heading",
      DROP COLUMN IF EXISTS "story_para1",
      DROP COLUMN IF EXISTS "story_para2",
      DROP COLUMN IF EXISTS "story_para3",
      DROP COLUMN IF EXISTS "story_para4",
      DROP COLUMN IF EXISTS "story_pullquote",
      DROP COLUMN IF EXISTS "story_para_final",
      DROP COLUMN IF EXISTS "phil1_title",
      DROP COLUMN IF EXISTS "phil1_body",
      DROP COLUMN IF EXISTS "phil2_title",
      DROP COLUMN IF EXISTS "phil2_body",
      DROP COLUMN IF EXISTS "phil3_title",
      DROP COLUMN IF EXISTS "phil3_body",
      DROP COLUMN IF EXISTS "mission_heading",
      DROP COLUMN IF EXISTS "mission_body1",
      DROP COLUMN IF EXISTS "mission_body2",
      DROP COLUMN IF EXISTS "mission_callout",
      DROP COLUMN IF EXISTS "pillar1_title",
      DROP COLUMN IF EXISTS "pillar1_body",
      DROP COLUMN IF EXISTS "pillar2_title",
      DROP COLUMN IF EXISTS "pillar2_body",
      DROP COLUMN IF EXISTS "pillar3_title",
      DROP COLUMN IF EXISTS "pillar3_body",
      DROP COLUMN IF EXISTS "pillar4_title",
      DROP COLUMN IF EXISTS "pillar4_body",
      DROP COLUMN IF EXISTS "curation_heading",
      DROP COLUMN IF EXISTS "curation_intro",
      DROP COLUMN IF EXISTS "crit1_title",
      DROP COLUMN IF EXISTS "crit1_body",
      DROP COLUMN IF EXISTS "crit2_title",
      DROP COLUMN IF EXISTS "crit2_body",
      DROP COLUMN IF EXISTS "crit3_title",
      DROP COLUMN IF EXISTS "crit3_body",
      DROP COLUMN IF EXISTS "crit4_title",
      DROP COLUMN IF EXISTS "crit4_body",
      DROP COLUMN IF EXISTS "ffl_body",
      DROP COLUMN IF EXISTS "ffl_card1_body",
      DROP COLUMN IF EXISTS "ffl_card2_body";
  `)
}
